// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oatxjvbzhnxmqghnrgvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hdHhqdmJ6aG54bXFnaG5yZ3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNDkxMDQsImV4cCI6MjA1MTgyNTEwNH0.91gJLz1ujExUwKft9MWLoJHG3G934OpRrzB0VhDG96s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);